"""
FitnessMate - 30 Workout Templates
Quick-start templates for one-tap workout logging.
"""

TEMPLATES = [
    # === כוח ביתי ===
    {
        "id": "home-strength-20",
        "name": "20 דק׳ כוח ביתי",
        "emoji": "🏠",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
    },
    {
        "id": "home-strength-30",
        "name": "30 דק׳ כוח ביתי",
        "emoji": "🏠",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 30,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
    },
    {
        "id": "home-strength-45",
        "name": "45 דק׳ כוח ביתי",
        "emoji": "🏠",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 45,
        "equipment": ["Bodyweight", "משקולות"],
        "location": "בבית",
        "category": "כוח",
    },
    {
        "id": "home-upper",
        "name": "20 דק׳ פלג גוף עליון",
        "emoji": "💪",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "חזה",
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
    },
    {
        "id": "home-legs",
        "name": "20 דק׳ רגליים ביתי",
        "emoji": "🦵",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "רגליים",
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
    },
    {
        "id": "home-abs",
        "name": "15 דק׳ בטן",
        "emoji": "🎯",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "בטן",
        "duration_minutes": 15,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
    },
    # === ריצה ===
    {
        "id": "run-20",
        "name": "20 דק׳ ריצה קלה",
        "emoji": "🏃",
        "workout_type": "ריצה בחוץ",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 20,
        "equipment": ["ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
    },
    {
        "id": "run-30",
        "name": "30 דק׳ ריצה בחוץ",
        "emoji": "🏃",
        "workout_type": "ריצה בחוץ",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
    },
    {
        "id": "run-45",
        "name": "45 דק׳ ריצה ארוכה",
        "emoji": "🏃‍♂️",
        "workout_type": "ריצה בחוץ",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 45,
        "equipment": ["ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
    },
    {
        "id": "run-intervals",
        "name": "25 דק׳ אינטרוולים",
        "emoji": "⚡",
        "workout_type": "ריצה בחוץ",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 25,
        "equipment": ["ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
    },
    {
        "id": "walk-30",
        "name": "30 דק׳ הליכה מהירה",
        "emoji": "🚶",
        "workout_type": "ריצה בחוץ",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
    },
    # === חדר כושר ===
    {
        "id": "gym-full-45",
        "name": "45 דק׳ חדר כושר מלא",
        "emoji": "🏋️",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 45,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
    },
    {
        "id": "gym-full-60",
        "name": "60 דק׳ חדר כושר מלא",
        "emoji": "🏋️",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 60,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
    },
    {
        "id": "gym-chest",
        "name": "40 דק׳ חזה + טרייספס",
        "emoji": "🏋️‍♂️",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "חזה",
        "duration_minutes": 40,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
    },
    {
        "id": "gym-back",
        "name": "40 דק׳ גב + ביי",
        "emoji": "🏋️",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "גב",
        "duration_minutes": 40,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
    },
    {
        "id": "gym-shoulders",
        "name": "35 דק׳ כתפיים",
        "emoji": "🏋️",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "כתפיים",
        "duration_minutes": 35,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
    },
    {
        "id": "gym-legs",
        "name": "45 דק׳ רגליים",
        "emoji": "🦵",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "רגליים",
        "duration_minutes": 45,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
    },
    {
        "id": "gym-cardio",
        "name": "30 דק׳ קרדיו מכשירים",
        "emoji": "🫀",
        "workout_type": "חדר כושר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["מכשירים"],
        "location": "חדר כושר",
        "category": "סיבולת",
    },
    # === משקולות ===
    {
        "id": "weights-20",
        "name": "20 דק׳ משקולות חופשיות",
        "emoji": "🏋️",
        "workout_type": "משקולות",
        "training_type": "כוח",
        "target_muscle": "זרועות",
        "duration_minutes": 20,
        "equipment": ["משקולות"],
        "location": "בבית",
        "category": "כוח",
    },
    {
        "id": "weights-30",
        "name": "30 דק׳ משקולות מלא",
        "emoji": "🏋️‍♂️",
        "workout_type": "משקולות",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 30,
        "equipment": ["משקולות"],
        "location": "בבית",
        "category": "כוח",
    },
    {
        "id": "weights-arms",
        "name": "25 דק׳ זרועות",
        "emoji": "💪",
        "workout_type": "משקולות",
        "training_type": "כוח",
        "target_muscle": "זרועות",
        "duration_minutes": 25,
        "equipment": ["משקולות"],
        "location": "בבית",
        "category": "כוח",
    },
    # === כדורגל ===
    {
        "id": "football-30",
        "name": "30 דק׳ כדורגל",
        "emoji": "⚽",
        "workout_type": "כדורגל עם הבן",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["Bodyweight", "ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
    },
    {
        "id": "football-45",
        "name": "45 דק׳ כדורגל",
        "emoji": "⚽",
        "workout_type": "כדורגל עם הבן",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 45,
        "equipment": ["Bodyweight", "ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
    },
    {
        "id": "football-60",
        "name": "60 דק׳ כדורגל משחק",
        "emoji": "⚽",
        "workout_type": "כדורגל עם הבן",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 60,
        "equipment": ["Bodyweight", "ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
    },
    # === מעורב / אחר ===
    {
        "id": "yoga-20",
        "name": "20 דק׳ יוגה",
        "emoji": "🧘",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "גמישות",
    },
    {
        "id": "yoga-30",
        "name": "30 דק׳ יוגה",
        "emoji": "🧘",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "גמישות",
    },
    {
        "id": "stretch-15",
        "name": "15 דק׳ מתיחות",
        "emoji": "🤸",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 15,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "גמישות",
    },
    {
        "id": "hiit-20",
        "name": "20 דק׳ HIIT",
        "emoji": "🔥",
        "workout_type": "אימון ביתי",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "סיבולת",
    },
    {
        "id": "hiit-30",
        "name": "30 דק׳ HIIT",
        "emoji": "🔥",
        "workout_type": "אימון ביתי",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "סיבולת",
    },
    {
        "id": "swim-30",
        "name": "30 דק׳ שחייה",
        "emoji": "🏊",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": [],
        "location": "בחוץ",
        "category": "סיבולת",
    },
    {
        "id": "bike-30",
        "name": "30 דק׳ אופניים",
        "emoji": "🚴",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": [],
        "location": "בחוץ",
        "category": "סיבולת",
    },
]


def get_template_by_id(template_id: str):
    for t in TEMPLATES:
        if t["id"] == template_id:
            return t
    return None


def get_templates_by_category(category: str):
    return [t for t in TEMPLATES if t["category"] == category]


def get_template_categories():
    return list({t["category"] for t in TEMPLATES})
