"""
FitnessMate - Workout Templates
Quick-start templates for one-tap workout logging.
Each template includes specific exercises with sets, reps and rest.
Context: microwave, zoom, kid, home, gym, outdoor
Gear: none, basic, full
"""

# Context → gear mapping for matching
CONTEXTS = {
    "microwave": {"label": "🍿 Microwave Hero", "desc": "2 דקות בזמן המיקרו", "max_duration": 4},
    "zoom": {"label": "💻 Zoom-Proof Core", "desc": "בזמן ישיבה/עבודה", "max_duration": 8},
    "kid": {"label": "👶 Kid-Toss Cardio", "desc": "עם ילדים", "max_duration": 20},
    "home": {"label": "🏠 Home Workout", "desc": "אימון ביתי", "max_duration": 60},
    "gym": {"label": "🏋️ Gym Time", "desc": "חדר כושר", "max_duration": 90},
    "outdoor": {"label": "🌳 Outdoor", "desc": "בחוץ", "max_duration": 60},
}

GEARS = {
    "none": {"label": "✋ Just Me", "desc": "בלי ציוד"},
    "basic": {"label": "🎒 Basic Gear", "desc": "משקולות קטנות / גומיות"},
    "full": {"label": "🏋️ Full Gym", "desc": "מכשירים מלאים"},
}

TEMPLATES = [
    # === MICRO WORKOUTS (2-4 min) ===
    {
        "id": "micro-stretch-2",
        "name": "2 דק׳ מתיחות מיקרו",
        "emoji": "🍿",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": "גוף מלא",
        "duration_minutes": 2,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "גמישות",
        "context": "microwave",
        "gear": "none",
        "exercises": [
            {"exercise_id": "neck_stretch", "sets": 1, "reps": 1, "rest_sec": 0},
            {"exercise_id": "shoulder_stretch", "sets": 1, "reps": 1, "rest_sec": 0},
            {"exercise_id": "quad_stretch", "sets": 1, "reps": 1, "rest_sec": 0},
        ],
        "warmup": [],
        "cooldown": [],
    },
    {
        "id": "micro-pushup-2",
        "name": "2 דק׳ שכיבות סמיכה",
        "emoji": "🍿",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "חזה",
        "duration_minutes": 2,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "microwave",
        "gear": "none",
        "exercises": [
            {"exercise_id": "pushup_standard", "sets": 2, "reps": 10, "rest_sec": 15},
        ],
        "warmup": [],
        "cooldown": [],
    },
    {
        "id": "micro-squat-2",
        "name": "2 דק׳ סקוואטים",
        "emoji": "🍿",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "רגליים",
        "duration_minutes": 2,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "microwave",
        "gear": "none",
        "exercises": [
            {"exercise_id": "squat_bodyweight", "sets": 2, "reps": 12, "rest_sec": 15},
        ],
        "warmup": [],
        "cooldown": [],
    },
    {
        "id": "micro-plank-2",
        "name": "2 דק׳ פלאנק",
        "emoji": "🍿",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "בטן",
        "duration_minutes": 2,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "microwave",
        "gear": "none",
        "exercises": [
            {"exercise_id": "plank", "sets": 2, "reps": 30, "rest_sec": 15},
        ],
        "warmup": [],
        "cooldown": [],
    },
    # === ZOOM / OFFICE (4-8 min, seated/standing) ===
    {
        "id": "zoom-neck-shoulders",
        "name": "5 דק׳ צוואר + כתפיים",
        "emoji": "💻",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": "כתפיים",
        "duration_minutes": 5,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "גמישות",
        "context": "zoom",
        "gear": "none",
        "exercises": [
            {"exercise_id": "neck_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "shoulder_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "arm_circles", "sets": 2, "reps": 10, "rest_sec": 0},
        ],
        "warmup": [],
        "cooldown": [],
    },
    {
        "id": "zoom-core-chair",
        "name": "5 דק׳ בטן על כיסא",
        "emoji": "💻",
        "workout_type": "אחר",
        "training_type": "כוח",
        "target_muscle": "בטן",
        "duration_minutes": 5,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "zoom",
        "gear": "none",
        "exercises": [
            {"exercise_id": "crunch", "sets": 2, "reps": 15, "rest_sec": 15},
            {"exercise_id": "russian_twist", "sets": 2, "reps": 15, "rest_sec": 15},
            {"exercise_id": "plank", "sets": 1, "reps": 30, "rest_sec": 0},
        ],
        "warmup": [],
        "cooldown": [],
    },
    {
        "id": "zoom-full-stretch",
        "name": "8 דק׳ מתיחות משרדיות",
        "emoji": "💻",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": "גוף מלא",
        "duration_minutes": 8,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "גמישות",
        "context": "zoom",
        "gear": "none",
        "exercises": [
            {"exercise_id": "neck_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "shoulder_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "chest_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "hip_flexor_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "cat_cow", "sets": 2, "reps": 10, "rest_sec": 0},
        ],
        "warmup": [],
        "cooldown": [],
    },
    # === KID WORKOUTS ===
    {
        "id": "kid-toss-cardio",
        "name": "15 דק׳ קרדיו עם ילדים",
        "emoji": "👶",
        "workout_type": "אימון ביתי",
        "training_type": "סיבולת",
        "target_muscle": "גוף מלא",
        "duration_minutes": 15,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "סיבולת",
        "context": "kid",
        "gear": "none",
        "exercises": [
            {"exercise_id": "jumping_jacks", "sets": 3, "reps": 15, "rest_sec": 20},
            {"exercise_id": "squat_bodyweight", "sets": 3, "reps": 10, "rest_sec": 20},
            {"exercise_id": "high_knees", "sets": 3, "reps": 15, "rest_sec": 20},
            {"exercise_id": "bear_crawl", "sets": 2, "reps": 5, "rest_sec": 20},
        ],
        "warmup": [],
        "cooldown": ["quad_stretch"],
    },
    {
        "id": "kid-strength-fun",
        "name": "10 דק׳ כוח משפחתי",
        "emoji": "👶",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 10,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "kid",
        "gear": "none",
        "exercises": [
            {"exercise_id": "pushup_standard", "sets": 2, "reps": 8, "rest_sec": 20},
            {"exercise_id": "squat_bodyweight", "sets": 2, "reps": 10, "rest_sec": 20},
            {"exercise_id": "plank", "sets": 2, "reps": 15, "rest_sec": 20},
        ],
        "warmup": [],
        "cooldown": [],
    },
    # === כוח ביתי ===
    {
        "id": "home-strength-20",
        "name": "20 דק׳ כוח ביתי",
        "emoji": "🏠",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "pushup_standard", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "squat_bodyweight", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "plank", "sets": 3, "reps": 30, "rest_sec": 30},
            {"exercise_id": "lunges", "sets": 2, "reps": 10, "rest_sec": 45},
        ],
        "warmup": ["jumping_jacks", "arm_circles"],
        "cooldown": ["chest_stretch", "quad_stretch"],
    },
    {
        "id": "home-strength-30",
        "name": "30 דק׳ כוח ביתי",
        "emoji": "🏠",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 30,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "pushup_standard", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "squat_bodyweight", "sets": 3, "reps": 15, "rest_sec": 45},
            {"exercise_id": "plank", "sets": 3, "reps": 30, "rest_sec": 30},
            {"exercise_id": "lunges", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "mountain_climber", "sets": 3, "reps": 15, "rest_sec": 30},
            {"exercise_id": "tricep_dip", "sets": 3, "reps": 10, "rest_sec": 45},
        ],
        "warmup": ["jumping_jacks", "arm_circles", "leg_swings"],
        "cooldown": ["chest_stretch", "quad_stretch", "shoulder_stretch"],
    },
    {
        "id": "home-strength-45",
        "name": "45 דק׳ כוח ביתי",
        "emoji": "🏠",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 45,
        "equipment": ["Bodyweight", "משקולות"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "basic",
        "exercises": [
            {"exercise_id": "pushup_standard", "sets": 3, "reps": 15, "rest_sec": 60},
            {"exercise_id": "squat_dumbbell", "sets": 3, "reps": 12, "rest_sec": 60},
            {"exercise_id": "row_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "shoulder_press_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "lunges_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "bicep_curl_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "plank", "sets": 3, "reps": 45, "rest_sec": 30},
            {"exercise_id": "russian_twist", "sets": 3, "reps": 20, "rest_sec": 30},
        ],
        "warmup": ["light_jog", "arm_circles", "leg_swings"],
        "cooldown": ["chest_stretch", "quad_stretch", "shoulder_stretch", "hamstring_stretch"],
    },
    {
        "id": "home-upper",
        "name": "20 דק׳ פלג גוף עליון",
        "emoji": "💪",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "חזה",
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "pushup_standard", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "pushup_wide", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "tricep_dip", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "pike_pushup", "sets": 3, "reps": 8, "rest_sec": 45},
            {"exercise_id": "superman", "sets": 3, "reps": 12, "rest_sec": 30},
        ],
        "warmup": ["arm_circles", "jumping_jacks"],
        "cooldown": ["chest_stretch", "shoulder_stretch", "tricep_stretch"],
    },
    {
        "id": "home-legs",
        "name": "20 דק׳ רגליים ביתי",
        "emoji": "🦵",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "רגליים",
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "squat_bodyweight", "sets": 3, "reps": 15, "rest_sec": 45},
            {"exercise_id": "lunges", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "glute_bridge", "sets": 3, "reps": 15, "rest_sec": 30},
            {"exercise_id": "calf_raises", "sets": 3, "reps": 15, "rest_sec": 30},
            {"exercise_id": "wall_sit", "sets": 3, "reps": 30, "rest_sec": 45},
        ],
        "warmup": ["jumping_jacks", "leg_swings"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "hip_flexor_stretch"],
    },
    {
        "id": "home-abs",
        "name": "15 דק׳ בטן",
        "emoji": "🎯",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "בטן",
        "duration_minutes": 15,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "crunch", "sets": 3, "reps": 15, "rest_sec": 30},
            {"exercise_id": "bicycle_crunch", "sets": 3, "reps": 20, "rest_sec": 30},
            {"exercise_id": "plank", "sets": 3, "reps": 30, "rest_sec": 30},
            {"exercise_id": "leg_raise", "sets": 3, "reps": 12, "rest_sec": 30},
            {"exercise_id": "mountain_climber", "sets": 3, "reps": 15, "rest_sec": 30},
        ],
        "warmup": ["light_jog", "hip_circles"],
        "cooldown": ["cat_cow", "yoga_child_pose"],
    },
    # === ריצה ===
    {
        "id": "run-20",
        "name": "20 דק׳ ריצה קלה",
        "emoji": "🏃",
        "workout_type": "ריצה בחוץ",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 20,
        "equipment": ["ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "running", "sets": 1, "reps": 20, "rest_sec": 0},
        ],
        "warmup": ["light_jog", "leg_swings", "hip_circles"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "calf_raises"],
    },
    {
        "id": "run-30",
        "name": "30 דק׳ ריצה בחוץ",
        "emoji": "🏃",
        "workout_type": "ריצה בחוץ",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "running", "sets": 1, "reps": 30, "rest_sec": 0},
        ],
        "warmup": ["light_jog", "leg_swings", "hip_circles"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "hip_flexor_stretch"],
    },
    {
        "id": "run-45",
        "name": "45 דק׳ ריצה ארוכה",
        "emoji": "🏃‍♂️",
        "workout_type": "ריצה בחוץ",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 45,
        "equipment": ["ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "running", "sets": 1, "reps": 45, "rest_sec": 0},
        ],
        "warmup": ["light_jog", "dynamic_stretch_full", "leg_swings"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "hip_flexor_stretch", "calf_raises"],
    },
    {
        "id": "run-intervals",
        "name": "25 דק׳ אינטרוולים",
        "emoji": "⚡",
        "workout_type": "ריצה בחוץ",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 25,
        "equipment": ["ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "sprint_intervals", "sets": 8, "reps": 1, "rest_sec": 60},
        ],
        "warmup": ["light_jog", "leg_swings", "butt_kicks", "high_knees"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "hip_flexor_stretch"],
    },
    {
        "id": "walk-30",
        "name": "30 דק׳ הליכה מהירה",
        "emoji": "🚶",
        "workout_type": "ריצה בחוץ",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "walking_fast", "sets": 1, "reps": 30, "rest_sec": 0},
        ],
        "warmup": ["leg_swings", "hip_circles"],
        "cooldown": ["quad_stretch", "hamstring_stretch"],
    },
    # === חדר כושר ===
    {
        "id": "gym-full-45",
        "name": "45 דק׳ חדר כושר מלא",
        "emoji": "🏋️",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 45,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
        "context": "gym",
        "gear": "full",
        "exercises": [
            {"exercise_id": "bench_press_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "lat_pulldown", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "shoulder_press_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "leg_press", "sets": 3, "reps": 12, "rest_sec": 60},
            {"exercise_id": "bicep_curl_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "tricep_extension_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "plank", "sets": 3, "reps": 30, "rest_sec": 30},
        ],
        "warmup": ["light_jog", "dynamic_stretch_full"],
        "cooldown": ["chest_stretch", "shoulder_stretch", "quad_stretch", "hamstring_stretch"],
    },
    {
        "id": "gym-full-60",
        "name": "60 דק׳ חדר כושר מלא",
        "emoji": "🏋️",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 60,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
        "context": "gym",
        "gear": "full",
        "exercises": [
            {"exercise_id": "bench_press_barbell", "sets": 4, "reps": 8, "rest_sec": 90},
            {"exercise_id": "lat_pulldown", "sets": 4, "reps": 10, "rest_sec": 60},
            {"exercise_id": "shoulder_press_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "squat_barbell", "sets": 4, "reps": 8, "rest_sec": 90},
            {"exercise_id": "row_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "bicep_curl_barbell", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "tricep_extension_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "crunch", "sets": 3, "reps": 15, "rest_sec": 30},
            {"exercise_id": "plank", "sets": 3, "reps": 45, "rest_sec": 30},
        ],
        "warmup": ["light_jog", "dynamic_stretch_full", "arm_circles"],
        "cooldown": ["chest_stretch", "shoulder_stretch", "quad_stretch", "hamstring_stretch", "tricep_stretch"],
    },
    {
        "id": "gym-chest",
        "name": "40 דק׳ חזה + טרייספס",
        "emoji": "🏋️‍♂️",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "חזה",
        "duration_minutes": 40,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
        "context": "gym",
        "gear": "full",
        "exercises": [
            {"exercise_id": "bench_press_barbell", "sets": 4, "reps": 8, "rest_sec": 90},
            {"exercise_id": "bench_press_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "chest_fly_dumbbell", "sets": 3, "reps": 12, "rest_sec": 60},
            {"exercise_id": "chest_press_machine", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "tricep_extension_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "tricep_kickback", "sets": 3, "reps": 12, "rest_sec": 45},
        ],
        "warmup": ["light_jog", "arm_circles", "pushup_incline"],
        "cooldown": ["chest_stretch", "tricep_stretch", "shoulder_stretch"],
    },
    {
        "id": "gym-back",
        "name": "40 דק׳ גב + ביי",
        "emoji": "🏋️",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "גב",
        "duration_minutes": 40,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
        "context": "gym",
        "gear": "full",
        "exercises": [
            {"exercise_id": "lat_pulldown", "sets": 4, "reps": 10, "rest_sec": 60},
            {"exercise_id": "seated_row_machine", "sets": 3, "reps": 12, "rest_sec": 60},
            {"exercise_id": "row_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "reverse_fly_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "bicep_curl_barbell", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "hammer_curl", "sets": 3, "reps": 12, "rest_sec": 45},
        ],
        "warmup": ["light_jog", "arm_circles"],
        "cooldown": ["shoulder_stretch", "cat_cow"],
    },
    {
        "id": "gym-shoulders",
        "name": "35 דק׳ כתפיים",
        "emoji": "🏋️",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "כתפיים",
        "duration_minutes": 35,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
        "context": "gym",
        "gear": "full",
        "exercises": [
            {"exercise_id": "shoulder_press_dumbbell", "sets": 4, "reps": 10, "rest_sec": 60},
            {"exercise_id": "lateral_raise_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "front_raise_dumbbell", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "reverse_fly_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "shrug_dumbbell", "sets": 3, "reps": 15, "rest_sec": 45},
        ],
        "warmup": ["arm_circles", "light_jog"],
        "cooldown": ["shoulder_stretch", "neck_stretch", "tricep_stretch"],
    },
    {
        "id": "gym-legs",
        "name": "45 דק׳ רגליים",
        "emoji": "🦵",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "רגליים",
        "duration_minutes": 45,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
        "context": "gym",
        "gear": "full",
        "exercises": [
            {"exercise_id": "squat_barbell", "sets": 4, "reps": 8, "rest_sec": 90},
            {"exercise_id": "leg_press", "sets": 3, "reps": 12, "rest_sec": 60},
            {"exercise_id": "lunges_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "leg_extension", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "leg_curl", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "calf_raises", "sets": 3, "reps": 15, "rest_sec": 30},
        ],
        "warmup": ["light_jog", "leg_swings", "hip_circles"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "hip_flexor_stretch"],
    },
    {
        "id": "gym-cardio",
        "name": "30 דק׳ קרדיו מכשירים",
        "emoji": "🫀",
        "workout_type": "חדר כושר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["מכשירים"],
        "location": "חדר כושר",
        "category": "סיבולת",
        "context": "gym",
        "gear": "full",
        "exercises": [
            {"exercise_id": "treadmill", "sets": 1, "reps": 10, "rest_sec": 0},
            {"exercise_id": "elliptical", "sets": 1, "reps": 10, "rest_sec": 0},
            {"exercise_id": "stationary_bike", "sets": 1, "reps": 10, "rest_sec": 0},
        ],
        "warmup": ["light_jog"],
        "cooldown": ["quad_stretch", "hamstring_stretch"],
    },
    # === משקולות ===
    {
        "id": "weights-20",
        "name": "20 דק׳ משקולות חופשיות",
        "emoji": "🏋️",
        "workout_type": "משקולות",
        "training_type": "כוח",
        "target_muscle": "זרועות",
        "duration_minutes": 20,
        "equipment": ["משקולות"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "basic",
        "exercises": [
            {"exercise_id": "bicep_curl_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "tricep_extension_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "hammer_curl", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "tricep_kickback", "sets": 3, "reps": 12, "rest_sec": 45},
        ],
        "warmup": ["arm_circles", "jumping_jacks"],
        "cooldown": ["tricep_stretch", "shoulder_stretch"],
    },
    {
        "id": "weights-30",
        "name": "30 דק׳ משקולות מלא",
        "emoji": "🏋️‍♂️",
        "workout_type": "משקולות",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 30,
        "equipment": ["משקולות"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "basic",
        "exercises": [
            {"exercise_id": "bench_press_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "row_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "shoulder_press_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "squat_dumbbell", "sets": 3, "reps": 12, "rest_sec": 60},
            {"exercise_id": "bicep_curl_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "tricep_extension_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
        ],
        "warmup": ["light_jog", "arm_circles", "leg_swings"],
        "cooldown": ["chest_stretch", "shoulder_stretch", "quad_stretch"],
    },
    {
        "id": "weights-arms",
        "name": "25 דק׳ זרועות",
        "emoji": "💪",
        "workout_type": "משקולות",
        "training_type": "כוח",
        "target_muscle": "זרועות",
        "duration_minutes": 25,
        "equipment": ["משקולות"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "basic",
        "exercises": [
            {"exercise_id": "bicep_curl_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "hammer_curl", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "concentration_curl", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "tricep_extension_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "tricep_kickback", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "wrist_curl", "sets": 2, "reps": 15, "rest_sec": 30},
        ],
        "warmup": ["arm_circles", "jumping_jacks"],
        "cooldown": ["tricep_stretch", "shoulder_stretch"],
    },
    # === כדורגל ===
    {
        "id": "football-30",
        "name": "30 דק׳ כדורגל",
        "emoji": "⚽",
        "workout_type": "כדורגל עם הבן",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["Bodyweight", "ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "football_drills", "sets": 1, "reps": 30, "rest_sec": 0},
        ],
        "warmup": ["light_jog", "leg_swings", "hip_circles"],
        "cooldown": ["quad_stretch", "hamstring_stretch"],
    },
    {
        "id": "football-45",
        "name": "45 דק׳ כדורגל",
        "emoji": "⚽",
        "workout_type": "כדורגל עם הבן",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 45,
        "equipment": ["Bodyweight", "ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "football_drills", "sets": 1, "reps": 15, "rest_sec": 0},
            {"exercise_id": "football_game", "sets": 1, "reps": 30, "rest_sec": 0},
        ],
        "warmup": ["light_jog", "leg_swings", "hip_circles"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "hip_flexor_stretch"],
    },
    {
        "id": "football-60",
        "name": "60 דק׳ כדורגל משחק",
        "emoji": "⚽",
        "workout_type": "כדורגל עם הבן",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 60,
        "equipment": ["Bodyweight", "ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "football_game", "sets": 1, "reps": 60, "rest_sec": 0},
        ],
        "warmup": ["light_jog", "dynamic_stretch_full", "leg_swings"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "hip_flexor_stretch", "calf_raises"],
    },
    # === מעורב / אחר ===
    {
        "id": "yoga-20",
        "name": "20 דק׳ יוגה",
        "emoji": "🧘",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "גמישות",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "yoga_sun_salutation", "sets": 3, "reps": 1, "rest_sec": 0},
            {"exercise_id": "yoga_warrior", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "yoga_downward_dog", "sets": 3, "reps": 1, "rest_sec": 0},
            {"exercise_id": "yoga_tree", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "yoga_child_pose", "sets": 2, "reps": 1, "rest_sec": 0},
        ],
        "warmup": ["cat_cow", "neck_stretch"],
        "cooldown": ["yoga_child_pose"],
    },
    {
        "id": "yoga-30",
        "name": "30 דק׳ יוגה",
        "emoji": "🧘",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "גמישות",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "yoga_sun_salutation", "sets": 5, "reps": 1, "rest_sec": 0},
            {"exercise_id": "yoga_warrior", "sets": 3, "reps": 1, "rest_sec": 0},
            {"exercise_id": "yoga_downward_dog", "sets": 3, "reps": 1, "rest_sec": 0},
            {"exercise_id": "yoga_tree", "sets": 3, "reps": 1, "rest_sec": 0},
            {"exercise_id": "plank", "sets": 2, "reps": 30, "rest_sec": 0},
            {"exercise_id": "yoga_child_pose", "sets": 3, "reps": 1, "rest_sec": 0},
        ],
        "warmup": ["cat_cow", "neck_stretch", "hip_circles"],
        "cooldown": ["yoga_child_pose", "hamstring_stretch"],
    },
    {
        "id": "stretch-15",
        "name": "15 דק׳ מתיחות",
        "emoji": "🤸",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 15,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "גמישות",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "neck_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "shoulder_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "chest_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "quad_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "hamstring_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "hip_flexor_stretch", "sets": 2, "reps": 1, "rest_sec": 0},
            {"exercise_id": "cat_cow", "sets": 3, "reps": 10, "rest_sec": 0},
        ],
        "warmup": ["light_jog"],
        "cooldown": ["yoga_child_pose"],
    },
    {
        "id": "hiit-20",
        "name": "20 דק׳ HIIT",
        "emoji": "🔥",
        "workout_type": "אימון ביתי",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "סיבולת",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "burpees", "sets": 3, "reps": 8, "rest_sec": 30},
            {"exercise_id": "jump_squat", "sets": 3, "reps": 10, "rest_sec": 30},
            {"exercise_id": "mountain_climber", "sets": 3, "reps": 15, "rest_sec": 30},
            {"exercise_id": "high_knees", "sets": 3, "reps": 20, "rest_sec": 30},
            {"exercise_id": "pushup_standard", "sets": 3, "reps": 10, "rest_sec": 30},
        ],
        "warmup": ["jumping_jacks", "light_jog"],
        "cooldown": ["quad_stretch", "chest_stretch", "hamstring_stretch"],
    },
    {
        "id": "hiit-30",
        "name": "30 דק׳ HIIT",
        "emoji": "🔥",
        "workout_type": "אימון ביתי",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "סיבולת",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "burpees", "sets": 4, "reps": 10, "rest_sec": 30},
            {"exercise_id": "jump_squat", "sets": 4, "reps": 12, "rest_sec": 30},
            {"exercise_id": "mountain_climber", "sets": 4, "reps": 20, "rest_sec": 30},
            {"exercise_id": "high_knees", "sets": 4, "reps": 20, "rest_sec": 30},
            {"exercise_id": "pushup_standard", "sets": 4, "reps": 12, "rest_sec": 30},
            {"exercise_id": "plank", "sets": 3, "reps": 30, "rest_sec": 30},
            {"exercise_id": "squat_bodyweight", "sets": 3, "reps": 15, "rest_sec": 30},
        ],
        "warmup": ["jumping_jacks", "light_jog", "dynamic_stretch_full"],
        "cooldown": ["quad_stretch", "chest_stretch", "hamstring_stretch", "hip_flexor_stretch"],
    },
    {
        "id": "swim-30",
        "name": "30 דק׳ שחייה",
        "emoji": "🏊",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": [],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "swimming", "sets": 1, "reps": 30, "rest_sec": 0},
        ],
        "warmup": ["arm_circles", "dynamic_stretch_full"],
        "cooldown": ["shoulder_stretch", "chest_stretch"],
    },
    {
        "id": "bike-30",
        "name": "30 דק׳ אופניים",
        "emoji": "🚴",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 30,
        "equipment": [],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "cycling", "sets": 1, "reps": 30, "rest_sec": 0},
        ],
        "warmup": ["leg_swings", "hip_circles"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "hip_flexor_stretch"],
    },
    # === תבניות חדשות ===
    {
        "id": "home-chest-bodyweight",
        "name": "20 דק׳ חזה ביתי",
        "emoji": "💪",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "חזה",
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "pushup_standard", "sets": 3, "reps": 15, "rest_sec": 45},
            {"exercise_id": "pushup_wide", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "pushup_diamond", "sets": 3, "reps": 8, "rest_sec": 45},
            {"exercise_id": "pushup_incline", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "dips_chest", "sets": 3, "reps": 8, "rest_sec": 45},
        ],
        "warmup": ["arm_circles", "jumping_jacks"],
        "cooldown": ["chest_stretch", "shoulder_stretch"],
    },
    {
        "id": "home-back-bodyweight",
        "name": "20 דק׳ גב ביתי",
        "emoji": "🔙",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "גב",
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "superman", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "inverted_row", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "back_extension", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "cat_cow", "sets": 3, "reps": 10, "rest_sec": 30},
        ],
        "warmup": ["arm_circles", "light_jog"],
        "cooldown": ["shoulder_stretch", "yoga_child_pose"],
    },
    {
        "id": "home-bands-full",
        "name": "25 דק׳ גומיות גוף מלא",
        "emoji": "🟡",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 25,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "squat_bands", "sets": 3, "reps": 15, "rest_sec": 45},
            {"exercise_id": "chest_fly_bands", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "row_bands", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "lateral_raise_bands", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "bicep_curl_bands", "sets": 3, "reps": 15, "rest_sec": 30},
            {"exercise_id": "tricep_pushdown_bands", "sets": 3, "reps": 12, "rest_sec": 30},
        ],
        "warmup": ["jumping_jacks", "arm_circles"],
        "cooldown": ["chest_stretch", "shoulder_stretch", "quad_stretch"],
    },
    {
        "id": "gym-arms",
        "name": "35 דק׳ זרועות חדר כושר",
        "emoji": "💪",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "זרועות",
        "duration_minutes": 35,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
        "context": "gym",
        "gear": "full",
        "exercises": [
            {"exercise_id": "bicep_curl_barbell", "sets": 4, "reps": 10, "rest_sec": 60},
            {"exercise_id": "hammer_curl", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "concentration_curl", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "skull_crusher", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "tricep_extension_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "wrist_curl", "sets": 2, "reps": 15, "rest_sec": 30},
        ],
        "warmup": ["arm_circles", "light_jog"],
        "cooldown": ["tricep_stretch", "shoulder_stretch"],
    },
    {
        "id": "gym-abs",
        "name": "20 דק׳ בטן חדר כושר",
        "emoji": "🎯",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "בטן",
        "duration_minutes": 20,
        "equipment": ["מכשירים"],
        "location": "חדר כושר",
        "category": "כוח",
        "context": "gym",
        "gear": "full",
        "exercises": [
            {"exercise_id": "crunch", "sets": 3, "reps": 20, "rest_sec": 30},
            {"exercise_id": "bicycle_crunch", "sets": 3, "reps": 20, "rest_sec": 30},
            {"exercise_id": "leg_raise", "sets": 3, "reps": 15, "rest_sec": 30},
            {"exercise_id": "russian_twist", "sets": 3, "reps": 20, "rest_sec": 30},
            {"exercise_id": "plank", "sets": 3, "reps": 45, "rest_sec": 30},
            {"exercise_id": "v_up", "sets": 3, "reps": 10, "rest_sec": 30},
        ],
        "warmup": ["light_jog", "hip_circles"],
        "cooldown": ["cat_cow", "yoga_child_pose"],
    },
    {
        "id": "outdoor-strength",
        "name": "30 דק׳ כוח בחוץ",
        "emoji": "🌳",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 30,
        "equipment": ["Bodyweight"],
        "location": "בחוץ",
        "category": "כוח",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "pushup_standard", "sets": 3, "reps": 15, "rest_sec": 45},
            {"exercise_id": "squat_bodyweight", "sets": 3, "reps": 15, "rest_sec": 45},
            {"exercise_id": "lunges", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "dips_chest", "sets": 3, "reps": 8, "rest_sec": 60},
            {"exercise_id": "inverted_row", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "plank", "sets": 3, "reps": 30, "rest_sec": 30},
        ],
        "warmup": ["light_jog", "dynamic_stretch_full"],
        "cooldown": ["chest_stretch", "quad_stretch", "hamstring_stretch"],
    },
    {
        "id": "outdoor-hiit",
        "name": "20 דק׳ HIIT בחוץ",
        "emoji": "🔥",
        "workout_type": "אימון ביתי",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "burpees", "sets": 4, "reps": 8, "rest_sec": 30},
            {"exercise_id": "sprint_intervals", "sets": 4, "reps": 1, "rest_sec": 60},
            {"exercise_id": "jump_squat", "sets": 3, "reps": 12, "rest_sec": 30},
            {"exercise_id": "high_knees", "sets": 3, "reps": 20, "rest_sec": 30},
            {"exercise_id": "lateral_shuffle", "sets": 3, "reps": 10, "rest_sec": 30},
        ],
        "warmup": ["light_jog", "dynamic_stretch_full"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "hip_flexor_stretch"],
    },
    {
        "id": "morning-wake",
        "name": "10 דק׳ התעוררות",
        "emoji": "☀️",
        "workout_type": "אחר",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 10,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "גמישות",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "yoga_sun_salutation", "sets": 3, "reps": 1, "rest_sec": 0},
            {"exercise_id": "cat_cow", "sets": 2, "reps": 10, "rest_sec": 0},
            {"exercise_id": "jumping_jacks", "sets": 2, "reps": 15, "rest_sec": 0},
            {"exercise_id": "squat_bodyweight", "sets": 2, "reps": 10, "rest_sec": 0},
        ],
        "warmup": ["neck_stretch"],
        "cooldown": ["shoulder_stretch"],
    },
    {
        "id": "weights-shoulders",
        "name": "25 דק׳ כתפיים + משקולות",
        "emoji": "🏋️",
        "workout_type": "משקולות",
        "training_type": "כוח",
        "target_muscle": "כתפיים",
        "duration_minutes": 25,
        "equipment": ["משקולות"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "basic",
        "exercises": [
            {"exercise_id": "shoulder_press_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "lateral_raise_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "front_raise_dumbbell", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "upright_row", "sets": 3, "reps": 10, "rest_sec": 45},
            {"exercise_id": "shrug_dumbbell", "sets": 3, "reps": 15, "rest_sec": 30},
        ],
        "warmup": ["arm_circles", "jumping_jacks"],
        "cooldown": ["shoulder_stretch", "neck_stretch"],
    },
    {
        "id": "weights-chest-back",
        "name": "30 דק׳ חזה + גב",
        "emoji": "🏋️‍♂️",
        "workout_type": "משקולות",
        "training_type": "כוח",
        "target_muscle": "חזה",
        "duration_minutes": 30,
        "equipment": ["משקולות"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "basic",
        "exercises": [
            {"exercise_id": "bench_press_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "row_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "chest_fly_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "reverse_fly_dumbbell", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "pullover_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
        ],
        "warmup": ["arm_circles", "light_jog"],
        "cooldown": ["chest_stretch", "shoulder_stretch"],
    },
    {
        "id": "weights-legs",
        "name": "25 דק׳ רגליים + משקולות",
        "emoji": "🦵",
        "workout_type": "משקולות",
        "training_type": "כוח",
        "target_muscle": "רגליים",
        "duration_minutes": 25,
        "equipment": ["משקולות"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "basic",
        "exercises": [
            {"exercise_id": "goblet_squat", "sets": 3, "reps": 12, "rest_sec": 60},
            {"exercise_id": "lunges_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "deadlift_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "single_leg_deadlift", "sets": 3, "reps": 8, "rest_sec": 60},
            {"exercise_id": "calf_raises", "sets": 3, "reps": 15, "rest_sec": 30},
        ],
        "warmup": ["leg_swings", "hip_circles", "light_jog"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "hip_flexor_stretch"],
    },
    {
        "id": "home-glutes",
        "name": "15 דק׳ ישבן ביתי",
        "emoji": "🍑",
        "workout_type": "אימון ביתי",
        "training_type": "כוח",
        "target_muscle": "רגליים",
        "duration_minutes": 15,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "כוח",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "glute_bridge", "sets": 3, "reps": 15, "rest_sec": 30},
            {"exercise_id": "sumo_squat", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "donkey_kick", "sets": 3, "reps": 12, "rest_sec": 30},
            {"exercise_id": "fire_hydrant", "sets": 3, "reps": 12, "rest_sec": 30},
            {"exercise_id": "reverse_lunge", "sets": 3, "reps": 10, "rest_sec": 45},
        ],
        "warmup": ["hip_circles", "leg_swings"],
        "cooldown": ["hip_flexor_stretch", "quad_stretch"],
    },
    {
        "id": "family-workout",
        "name": "20 דק׳ אימון משפחתי",
        "emoji": "👨‍👩‍👧‍👦",
        "workout_type": "אימון ביתי",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 20,
        "equipment": ["Bodyweight"],
        "location": "בבית",
        "category": "סיבולת",
        "context": "home",
        "gear": "none",
        "exercises": [
            {"exercise_id": "jumping_jacks", "sets": 3, "reps": 15, "rest_sec": 30},
            {"exercise_id": "squat_bodyweight", "sets": 3, "reps": 10, "rest_sec": 30},
            {"exercise_id": "high_knees", "sets": 3, "reps": 15, "rest_sec": 30},
            {"exercise_id": "bear_crawl", "sets": 2, "reps": 5, "rest_sec": 30},
            {"exercise_id": "plank", "sets": 2, "reps": 20, "rest_sec": 30},
        ],
        "warmup": ["jumping_jacks", "arm_circles"],
        "cooldown": ["quad_stretch", "shoulder_stretch"],
    },
    {
        "id": "walk-45",
        "name": "45 דק׳ הליכה",
        "emoji": "🚶",
        "workout_type": "ריצה בחוץ",
        "training_type": "סיבולת",
        "target_muscle": None,
        "duration_minutes": 45,
        "equipment": ["ריצה"],
        "location": "בחוץ",
        "category": "סיבולת",
        "context": "outdoor",
        "gear": "none",
        "exercises": [
            {"exercise_id": "walking_fast", "sets": 1, "reps": 45, "rest_sec": 0},
        ],
        "warmup": ["leg_swings", "hip_circles"],
        "cooldown": ["quad_stretch", "hamstring_stretch", "calf_raises"],
    },
    {
        "id": "gym-upper-lower-split",
        "name": "50 דק׳ עליון/תחתון",
        "emoji": "🏋️",
        "workout_type": "חדר כושר",
        "training_type": "כוח",
        "target_muscle": "גוף מלא",
        "duration_minutes": 50,
        "equipment": ["מכשירים", "משקולות"],
        "location": "חדר כושר",
        "category": "כוח",
        "context": "gym",
        "gear": "full",
        "exercises": [
            {"exercise_id": "bench_press_dumbbell", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "lat_pulldown", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "shoulder_press_machine", "sets": 3, "reps": 10, "rest_sec": 60},
            {"exercise_id": "squat_barbell", "sets": 4, "reps": 8, "rest_sec": 90},
            {"exercise_id": "leg_curl", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "leg_extension", "sets": 3, "reps": 12, "rest_sec": 45},
            {"exercise_id": "plank", "sets": 3, "reps": 30, "rest_sec": 30},
        ],
        "warmup": ["light_jog", "dynamic_stretch_full"],
        "cooldown": ["chest_stretch", "quad_stretch", "hamstring_stretch", "shoulder_stretch"],
    },
]


def get_template_by_id(template_id: str):
    for t in TEMPLATES:
        if t["id"] == template_id:
            return t
    return None


def get_templates_by_category(category: str):
    return [t for t in TEMPLATES if t["category"] == category]


def get_template_categories():
    return list({t["category"] for t in TEMPLATES})


def match_templates(context=None, gear=None, muscle=None):
    """Match templates by context, gear, and muscle group.
    Returns filtered list sorted by best match."""
    results = TEMPLATES

    if context:
        results = [t for t in results if t.get("context") == context]

    if gear:
        # "none" matches all; "basic" matches none+basic; "full" matches all
        if gear == "none":
            results = [t for t in results if t.get("gear") in ("none",)]
        elif gear == "basic":
            results = [t for t in results if t.get("gear") in ("none", "basic")]
        # "full" matches everything

    if muscle:
        if muscle == "גוף מלא":
            results = [t for t in results if t.get("target_muscle") in ("גוף מלא", None)]
        elif muscle == "הפתעה":
            # Random - return all and let caller pick
            pass
        else:
            # Match specific muscle OR full body
            results = [t for t in results
                       if t.get("target_muscle") == muscle
                       or t.get("target_muscle") == "גוף מלא"]

    return results
